batch_size: 8
crop_size:
  - 256
  - 256
  - 256
detection_folders:
- TRA
dropout: 0.01
example_images: False  # Slow
input_train:
- track_data/embryo3
- track_data/embryo4
- track_data/embryo5
input_val:
- track_data/embryo6
max_tokens: 2048
name: example
ndim: 3
num_decoder_layers: 5
num_encoder_layers: 5
outdir: runs
distributed: False
window: 6